/*
 * Bluetooth.c
 *
 *  Created on: Jun 1, 2020
 *      Author: Anthony
 */


void initScreen(){
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 10;
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'W';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'e';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'l';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'c';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'm';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'e';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 't';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'J';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'h';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'n';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'W';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'i';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'l';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'k';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'e';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 's';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'B';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'l';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'u';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'e';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 't';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 't';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'h';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 10;
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'P';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'r';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'e';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 's';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 's';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = '1';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ',';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = '2';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ',';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'r';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = '3';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 't';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'C';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'n';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 't';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'r';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'o';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'l';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'a';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = ' ';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'f';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'a';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = 'n';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
      EUSCI_A2->TXBUF = '!';
      while(!(EUSCI_A2->IFG & EUSCI_A_IFG_TXIFG));
}
